service: Production-Ready-Serverless-NestJS
frameworkVersion: '>=3'

plugins:
  - serverless-plugin-warmup-ts-bridge-v2 # this needs to go before the warmup plugin
  - serverless-plugin-warmup # this needs to go before the typescript plugin
  - serverless-plugin-typescript
  - serverless-offline

package:
  patterns:
    - "**/*.gql"
    - '!dist/**'

custom:
  warmup:
    default:
      enabled: true
      prewarm: true # Run WarmUp immediately after a deployment
      timeout: 16 # One second longer than main lambda timeout
      vpc: false # ensure WarmUp lambda isn't launched in a VPC

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 15
  region: us-east-1
  logRetentionInDays: 14
  # vpc:
  #   securityGroupIds:
  #     - 
  #   subnetIds:
  #     - 

functions:
  main:
    handler: src/lambda.handler
    environment:
      NODE_ENV: production
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
